apiVersion: batch/v1
kind: Job
metadata:
  name: botjob
spec:
  template:
    metadata:
      name: botjob
    spec:
      containers:
      - name: traderbot
        image: gcr.io/traider-project/iptest@sha256:31228f03bb80055a636c73e94f62107813d1763e563e289fc1a21e799d849331
      restartPolicy: Never
