apiVersion: batch/v1
kind: Job
metadata:
  name: botjob
spec:
  template:
    metadata:
      name: botjob
    spec:
      containers:
      - env:
        - name: TOKEN
          valueFrom:
            configMapKeyRef:
              key: TOKEN
              name: traderbot-test1-config-oklg
        - name: WEBHOOK_NOTIFICATION_CENTER
          valueFrom:
            configMapKeyRef:
              key: WEBHOOK_NOTIFICATION_CENTER
              name: traderbot-test1-config-oklg
        - name: SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: SERVICE_URL
              name: traderbot-test1-config-oklg
        - name: APIKEY
          valueFrom:
            configMapKeyRef:
              key: APIKEY
              name: traderbot-test1-config-oklg
        - name: CHATID
          valueFrom:
            configMapKeyRef:
              key: CHATID
              name: traderbot-test1-config-oklg
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: traderbot-test1-config-oklg
        image: gcr.io/traider-project/traderbot@sha256:4487b64d2d0c1e35f9c5b593ef2da5ec163aa8de8f7543474677f50976df51ab
      restartPolicy: Never
