apiVersion: batch/v1
kind: Job
metadata:
  name: traderbot-job4
spec:
  template:
    metadata:
      name: traderbot-job4
    spec:
      containers:
      - name: traderbot-job4
        image: gcr.io/traider-project/traderbot@sha256:37d096271c004273129eeb8f47e453d4bbd6e8c11ccda7453a417c113b007f77
        env:
        - name: TOKEN
          value: "bdda46f2-96b0-41d4-9720-171272e8e0a5"
        - name: APIKEY
          value: "7E07C87E-FD71-4C4A-A326-929DA206D9F9"
        - name: SERVICE_URL
          value: "http://wa-traider-bot-api.azurewebsites.net/api/"
        - name: WEBHOOK_NOTIFICATION_CENTER
          value: "http://wa-clever-bots.azurewebsites.net/api/webhook/botStarted"
        - name: CHATID
          value: "460121491"
        - name: MONGODB
          value: "mongodb://127.0.0.1:27017"
        resources:
          requests:
            cpu: 50m
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 50m
        volumeMounts:
        - mountPath: /data/db
          name: mongodata
      restartPolicy: OnFailure
      volumes:
      - name: mongodata
