apiVersion: batch/v1
kind: Job
metadata:
  name: traderbot-job1
spec:
  template:
    metadata:
      name: traderbot-job1
    spec:
      containers:
      - name: traderbot-job1
        image: gcr.io/traider-project/traderbot@sha256:102c74c1f82e39ee5a6c93e0e51921c22ef44af1a0e5c972e167f149e8ddab74
        env:
        - name: TOKEN
          value: "ea609998-1a26-4ac8-9987-83ef7ade1f08"
        - name: APIKEY
          value: "7E07C87E-FD71-4C4A-A326-929DA206D9F9"
        - name: SERVICE_URL
          value: "http://wa-traider-bot-api.azurewebsites.net/api/"
        - name: WEBHOOK_NOTIFICATION_CENTER
          value: "http://wa-clever-bots.azurewebsites.net/api/webhook/botStarted"
        - name: CHATID
          value: "499464041"
        - name: MONGODB
          value: "mongodb://127.0.0.1:27017"
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources:
        - requests:
          - cpu: 50m
        volumeMounts:
        - mountPath: /data/db
          name: mongodata
      restartPolicy: Never
      volumes:
      - name: mongodata
