apiVersion: batch/v1
kind: Job
metadata:
  name: traderbot-job1
spec:
  template:
    metadata:
      name: traderbot-job1
    spec:
      containers:
      - name: traderbot-job1
        image: gcr.io/traider-project/traderbot@sha256:54e42f04eb5b230a548ebf1f0b16d1fb5664049d3e04e3cd62f86f589cf9f608
        env:
        - name: TOKEN
          value: "ea609998-1a26-4ac8-9987-83ef7ade1f08"
        - name: APIKEY
          value: "7E07C87E-FD71-4C4A-A326-929DA206D9F9"
        - name: SERVICE_URL
          value: "http://wa-traider-bot-api.azurewebsites.net/api/"
        - name: WEBHOOK_NOTIFICATION_CENTER
          value: "http://wa-clever-bots.azurewebsites.net/api/webhook/botStarted"
        - name: CHATID
          value: "499464041"
        - name: MONGODB
          value: "mongodb://mongo:27017"
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodata
      restartPolicy: Never
      volumes:
      - name: mongodata
